<?PHP

define("PAYHERE_MERCHENT_ID", "1228631");
define("PAYHERE_SANDBOX", true);
define("PAYHERE_API_KEY","NE9WeGdJYnNLZEU0SkVWaDZvS2R5TDNIRjo4bjBkejZDUlByRzRLQnFjTnRWaHRSNE9jUkJTbkdkaEc0VXNUbUY3RXpseg==");